name: Validate Compatibility Documentation

on:
  push:
    paths:
      - 'docs/compatibility/**'
  pull_request:
    paths:
      - 'docs/compatibility/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate compatibility documentation
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml markdown frontmatter

      - name: Check client report format
        run: |
          python .github/scripts/validate_client_reports.py
          
      - name: Update compatibility matrix
        if: github.event_name != 'pull_request'
        run: |
          python .github/scripts/update_compatibility_matrix.py
          
      - name: Check progress consistency
        run: |
          python .github/scripts/check_progress_consistency.py
          
      - name: Commit updated matrix if changed
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/compatibility/index.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update compatibility matrix [skip ci]"
          git push